name: Simple build - 1

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Build the code
      run: cd 1 && bazel build //:app;
    
    - name: Execute application
      run: ./1/bazel-out/k8-fastbuild/bin/app;